# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tf_dp <- function(n, y, lam) {
    .Call(`_clever_tf_dp`, n, y, lam)
}

pcatf_core <- function(X, U, V, d, lambda, K, maxiter, solveV, verbose, tol) {
    .Call(`_clever_pcatf_core`, X, U, V, d, lambda, K, maxiter, solveV, verbose, tol)
}

